name: Build

on:
  workflow_call:
    inputs:
      version:
        description: The version of the artifacts to be built
        type: string
        required: true
      publish-artifacts:
        description: Whether the artifacts should be published (true/false)
        type: boolean
        default: false
      update-latest-tag:
        description: Whether the latest tag should be updated to the current build (true/false)
        type: boolean
        default: false
    secrets:
      docker-hub-token:
        required: false
        description: Docker Hub token

permissions:
  contents: read
  packages: read

env:
  IMAGE_TAG_BASE: "nadunrds/debug-tools"

jobs:
  run-super-linter:
    name: Run GitHub Super Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Lint Code Base
        uses: super-linter/super-linter@ffde3b2b33b745cb612d787f669ef9442b1339a6 # v8.1.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          IGNORE_GITIGNORED_FILES: "true"
          KUBERNETES_KUBECONFORM_OPTIONS: "--ignore-missing-schemas"
          VALIDATE_JAVASCRIPT_STANDARD: "false"
          VALIDATE_PYTHON_PYLINT: "false"
          VALIDATE_BIOME_FORMAT: "false"

  run-vulnerability-analysis:
    name: Run Vulnerability Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: fs
          vuln-type: library
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c3d42c5d08633d8b33635fbd94b000a0e2585b3c # v3.31.4
        if: always()
        with:
          sarif_file: trivy-results.sarif

  test-docker-images:
    name: Test Docker Images
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.13.7"
      - name: Set up Docker
        uses: docker/setup-docker-action@efe9e3891a4f7307e689f2100b33a155b900a608 # v4.5.0
      - name: Setup pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
      - name: Setup Poetry
        run: pipx install poetry
      - name: Install Test Dependencies
        run: poetry sync
      - name: Validate Types in Tests
        run: poetry run mypy .
      - name: Run Tests
        run: poetry run pytest

  build-tools:
    name: Build Tools
    runs-on: ubuntu-latest
    needs:
      - run-super-linter
      - run-vulnerability-analysis
      - test-docker-images
    strategy:
      matrix:
        tool:
          - "request-debugger"
          - "debug-container"
    steps:
      - name: Checkout Code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - id: generate-artifacts-version
        name: Generate Artifacts Version
        env:
          ARTIFACTS_VERSION: ${{ inputs.version }}
        run: |
          echo "artifacts-version=${ARTIFACTS_VERSION/\//-}" >> "${GITHUB_OUTPUT}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          install: true
      - name: Available platforms
        run: echo "${SUPPORTED_PLATFORMS}"
        env:
          SUPPORTED_PLATFORMS: ${{ steps.buildx.outputs.platforms }}
      - name: Build Docker Image for scanning
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./components/${{ matrix.tool }}
          load: true
          tags: ${{ env.IMAGE_TAG_BASE }}-${{ matrix.tool }}:${{ steps.generate-artifacts-version.outputs.artifacts-version }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          image-ref: ${{ env.IMAGE_TAG_BASE }}-${{ matrix.tool }}:${{ steps.generate-artifacts-version.outputs.artifacts-version }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true

      - name: Login to the Container registry
        if: ${{ inputs.publish-artifacts == true }}
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: nadunrds
          password: ${{ secrets.docker-hub-token }}
      - name: Build & Push Docker Image
        if: ${{ inputs.publish-artifacts == true }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./components/${{ matrix.tool }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAG_BASE }}-${{ matrix.tool }}:${{ steps.generate-artifacts-version.outputs.artifacts-version }}
      - name: Build & Push Docker Image with latest Tag
        if: ${{ inputs.publish-artifacts == true && inputs.update-latest-tag == true }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./components/${{ matrix.tool }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAG_BASE }}-${{ matrix.tool }}:latest
